name: smart_firebase_fcm
description: A plug-and-play modular Firebase FCM package with local notifications, redirection, and manual feature toggles (analytics, crashlytics, etc.).
version: 1.0.14
homepage: https://github.com/jadejadivyaraj04/smart_firebase_fcm
repository: https://github.com/jadejadivyaraj04/smart_firebase_fcm
issue_tracker: https://github.com/jadejadivyaraj04/smart_firebase_fcm/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  smart_firebase_fcm_generator: smart_firebase_fcm_generator
  ios_setup_helper: ios_setup_helper
